FROM ubuntu:noble

RUN apt-get update &&                               \
    apt-get install -y                              \
                    --no-install-recommends         \
                    --no-install-suggests           \
                                                    \
                    make                            \
                    fonts-liberation                \
                    latexmk                         \
                    texlive-xetex                   \
                    texlive-lang-english            \
                    texlive-lang-cyrillic           \
                    texlive-fonts-recommended       \
                    texlive-extra-utils
